[project]
name = "pi-scan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "kivy>=2.3.1",
    "pillow>=11.3.0",
    "pydbus>=0.6.0",
    "vext>=0.7.6",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "gphoto2>=2.6.1 ; sys_platform == 'linux'",
    "ruff>=0.12.2",
    "vermin>=1.6.0",
]

# Run with `uv run ruff check`
[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
extend-select = ["E", "F"]

